FROM node:22.13-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/indexer/package.json apps/indexer/package.json

RUN npm ci --workspace apps/indexer --include-workspace-root=false --include=dev

COPY apps/indexer apps/indexer

CMD ["npm", "run", "dev", "-w", "apps/indexer"]
