[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 999999
evm_version = "istanbul"

remappings = [
  "contracts/=lib/v2-core/contracts/",
  "@uniswap/v2-core/=lib/v2-core/",
  "@uniswap/v2-periphery/=lib/v2-periphery/",
  "@uniswap/lib/=lib/solidity-lib/"
]

[fmt]
line_length = 120
