"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { formatEther, parseEther } from "viem";
import { useAccount, usePublicClient, useReadContract, useWriteContract } from "wagmi";
import { ChevronLeft, ChevronRight, ExternalLink, Grid2X2, ImagePlus, List as ListIcon, Loader2, Search, ShoppingBag, Sparkles } from "lucide-react";
import { blueEditionAbi, bluePFPAbi, ipfsGateway, nftAddresses, nftControllerForDeployment, nftDropControllerAbi, nftFeePolicyAbi, nftLaunchpadEnabled, nftMarketplaceForDeployment, nftMarketplaceAbi, type NFTDeployment } from "@/lib/nft-contracts";
import { PFPMintMarket } from "./pfp-mint-market";
import { NFTCollectionTabs } from "../../nft-collection-tabs";
import { NFTCollectionProfile } from "../../nft-collection-profile";
import { NFTCommerceDialog } from "../../nft-commerce-dialog";
import { NFTOffersPanel } from "../../nft-offers-panel";
import { MintPhaseStatus } from "@/components/nft-mint-schedule";
import { useNFTMintPhase } from "@/lib/use-nft-mint-phase";
import { useNFTAllowlistProof } from "@/lib/use-nft-allowlist-proof";
import { optimizedTokenImageUrl } from "@/lib/token-metadata";
import { NFTQuickBuyDialog, type NFTQuickBuyItem } from "../../nft-quick-buy-dialog";

export function NFTMintMarket({ collection, tokenId, view = "item", standard, deployment = "current" }: { collection: `0x${string}`; tokenId: bigint; view?: "item" | "collection"; standard?: "ERC721" | "ERC1155"; deployment?: NFTDeployment }) {
  const pfp = useReadContract({ address: collection, abi: bluePFPAbi, functionName: "supportsInterface", args: ["0x80ac58cd"], chainId: 8453, query: { enabled: !standard } });
  if (!standard && pfp.isLoading) return <section className="loading-shell" aria-label="Loading NFT"><div className="loading-hero"/></section>;
  if (standard === "ERC721" || (!standard && pfp.data)) return <PFPMintMarket collection={collection} tokenId={tokenId} view={view} deployment={deployment}/>;
  return <EditionMintMarket collection={collection} tokenId={tokenId} view={view} deployment={deployment}/>;
}

function EditionMintMarket({ collection, tokenId, view, deployment }: { collection: `0x${string}`; tokenId: bigint; view: "item" | "collection"; deployment: NFTDeployment }) {
  const { address, isConnected } = useAccount(); const { writeContractAsync, isPending } = useWriteContract();
  const publicClient = usePublicClient({ chainId: 8453 });
  const [quantity, setQuantity] = useState("1");
  const [metadata, setMetadata] = useState<{ name?: string; description?: string; image?: string }>({}); const [collectionMetadata, setCollectionMetadata] = useState<CollectionMetadata>({}); const [notice, setNotice] = useState("");
  const [saleQuantity, setSaleQuantity] = useState("1"); const [salePrice, setSalePrice] = useState("0.1");
  const controllerAddress = nftControllerForDeployment(deployment);
  const marketAddress = nftMarketplaceForDeployment(deployment, "ERC1155");
  const [listingId, setListingId] = useState(""); const [listingMarketplace, setListingMarketplace] = useState<`0x${string}`>(marketAddress); const [buyQuantity, setBuyQuantity] = useState("1");
  const [commerceDialog, setCommerceDialog] = useState<"buy" | "list" | null>(null); const [listingDays, setListingDays] = useState("30");
  const name = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "name", chainId: 8453 });
  const symbol = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "symbol", chainId: 8453 });
  const owner = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "owner", chainId: 8453 });
  const royaltyBps = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "royaltyBps", chainId: 8453 });
  const marketplaceFeeBps = useReadContract({ address: nftAddresses.feePolicy, abi: nftFeePolicyAbi, functionName: "marketplaceFeeBps", chainId: 8453, query: { enabled: nftLaunchpadEnabled } });
  const uri = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "uri", args: [tokenId], chainId: 8453 });
  const contractURI = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "contractURI", chainId: 8453 });
  const max = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "maxSupply", args: [tokenId], chainId: 8453 });
  const minted = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "lifetimeMinted", args: [tokenId], chainId: 8453 });
  const { phaseId, phaseData, nowSeconds, isLoading: phaseLoading } = useNFTMintPhase(collection, tokenId, controllerAddress, nftLaunchpadEnabled);
  const phaseType = Number(phaseData?.[0] ?? 0); const allowlistProof = useNFTAllowlistProof(collection, tokenId, phaseId, address, phaseType === 1);
  const mintedInPhase = useReadContract({ address: controllerAddress, abi: nftDropControllerAbi, functionName: "phaseMinted", args: [collection, tokenId, phaseId], chainId: 8453, query: { enabled: nftLaunchpadEnabled && phaseId > 0n } });
  const walletMintedInPhase = useReadContract({ address: controllerAddress, abi: nftDropControllerAbi, functionName: "mintedByWalletInPhase", args: [collection, tokenId, phaseId, address!], chainId: 8453, query: { enabled: nftLaunchpadEnabled && phaseId > 0n && Boolean(address) } });
  const walletMintedTotal = useReadContract({ address: controllerAddress, abi: nftDropControllerAbi, functionName: "mintedByWalletTotal", args: [collection, tokenId, address!], chainId: 8453, query: { enabled: nftLaunchpadEnabled && Boolean(address) } });
  const approved = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "isApprovedForAll", args: [address!, marketAddress], chainId: 8453, query: { enabled: Boolean(address) && nftLaunchpadEnabled } });
  const balance = useReadContract({ address: collection, abi: blueEditionAbi, functionName: "balanceOf", args: [address!, tokenId], chainId: 8453, query: { enabled: Boolean(address) } });
  const parsedListingId = safePositiveBigInt(listingId) ?? 0n;
  const selectedListing = useReadContract({ address: listingMarketplace, abi: nftMarketplaceAbi, functionName: "listings", args: [parsedListingId], chainId: 8453, query: { enabled: nftLaunchpadEnabled && parsedListingId > 0n } });
  const unitPrice = phaseType === 0 ? phaseData?.[3] ?? 0n : allowlistProof.entry?.unitPrice ?? 0n;
  const phaseActive = Boolean(phaseData && !phaseData[11] && nowSeconds >= phaseData[4] && nowSeconds < phaseData[5]);
  const maxPerTransaction = BigInt(phaseData?.[8] ?? 0);
  const collectionRemaining = max.data && minted.data !== undefined ? max.data > minted.data ? max.data - minted.data : 0n : 0n;
  const phaseRemaining = phaseData ? remaining(phaseData[6], mintedInPhase.data ?? 0n) : 0n;
  const walletUsed = phaseData?.[1] === 0 ? walletMintedInPhase.data ?? 0n : walletMintedTotal.data ?? 0n;
  const walletCap = phaseType === 0 ? BigInt(phaseData?.[7] ?? 0) : allowlistProof.entry?.allowance ?? 0n;
  const walletRemaining = phaseData ? remaining(walletCap, walletUsed) : 0n;
  const mintLimit = minPositive(maxPerTransaction, collectionRemaining, phaseRemaining, walletRemaining);
  const requestedMintAmount = safePositiveBigInt(quantity);
  const allowlistReady = phaseType === 0 || Boolean(allowlistProof.entry);
  const canMint = Boolean(isConnected && address && phaseData && phaseActive && requestedMintAmount && mintLimit > 0n && requestedMintAmount <= mintLimit && allowlistReady && !isPending);
  const mintAvailability = !phaseData ? phaseLoading ? "Loading mint configuration…" : "No mint phase is configured." : nowSeconds < phaseData[4] ? "Mint has not opened yet." : nowSeconds >= phaseData[5] ? "This mint phase has ended." : mintLimit === 0n ? "No mint allowance remains for this wallet or edition." : requestedMintAmount && requestedMintAmount > mintLimit ? `Maximum available in this transaction: ${mintLimit}.` : !isConnected ? "Connect your wallet to mint." : "The NFT is sent directly to your wallet.";
  const listingMatchesItem = Boolean(selectedListing.data && selectedListing.data[1].toLowerCase() === collection.toLowerCase() && selectedListing.data[2] === tokenId && selectedListing.data[6] > 0n && !selectedListing.data[7] && selectedListing.data[4] <= nowSeconds && selectedListing.data[5] > nowSeconds);
  const isListingSeller = Boolean(address && selectedListing.data?.[0].toLowerCase() === address.toLowerCase());
  const ownsEdition = (balance.data ?? 0n) > 0n;
  const mintFinished = Boolean(phaseData && (phaseData[11] || nowSeconds >= phaseData[5] || (max.data ?? 0n) <= (minted.data ?? 0n)));
  const isOwner = Boolean(address && owner.data?.toLowerCase() === address.toLowerCase());

  useEffect(() => { if (!uri.data) return; fetch(ipfsGateway(uri.data)).then((r) => r.ok ? r.json() : {}).then(setMetadata).catch(() => undefined); }, [uri.data]);
  useEffect(() => { if (!contractURI.data) return; fetch(ipfsGateway(contractURI.data)).then((r) => r.ok ? r.json() : {}).then(setCollectionMetadata).catch(() => undefined); }, [contractURI.data]);
  useEffect(() => { fetch(`/api/nft/listing?collection=${collection}&tokenId=${tokenId}`).then((response) => response.ok ? response.json() : {}).then((data: { listingId?: string;marketplace?:`0x${string}` }) => {setListingId(data.listingId || "");if(data.marketplace)setListingMarketplace(data.marketplace);}).catch(() => undefined); }, [collection, tokenId]);

  async function mint() {
    if (!address || !phaseData) return; setNotice(""); const amount = safePositiveBigInt(quantity); const deadline = BigInt(Math.floor(Date.now()/1000)+900);
    try {
      if (!amount) throw new Error("Enter a valid mint quantity.");
      const hash=phaseType===0?await writeContractAsync({ chainId:8453,address:controllerAddress,abi:nftDropControllerAbi,functionName:"mintPublic",value:unitPrice*amount,args:[collection,tokenId,phaseId,amount,address,unitPrice,deadline] }):allowlistProof.entry?await writeContractAsync({ chainId:8453,address:controllerAddress,abi:nftDropControllerAbi,functionName:"mintAllowlist",value:unitPrice*amount,args:[collection,tokenId,phaseId,amount,address,allowlistProof.entry.allowance,unitPrice,deadline,allowlistProof.entry.proof] }):(()=>{throw new Error("This wallet is not eligible for the allowlist phase.");})();
      setNotice("Mint submitted. Waiting for Base confirmation…");await publicClient?.waitForTransactionReceipt({hash});setNotice("Mint confirmed. Balances are updating.");void minted.refetch();void balance.refetch();void walletMintedInPhase.refetch();void walletMintedTotal.refetch();
    } catch (error) { setNotice(shortError(error)); }
  }
  async function approveOrList() {
    try { if (!approved.data){const approvalHash=await writeContractAsync({chainId:8453,address:collection,abi:blueEditionAbi,functionName:"setApprovalForAll",args:[marketAddress,true]});setNotice("Approval submitted. Waiting for confirmation…");await publicClient?.waitForTransactionReceipt({hash:approvalHash});await approved.refetch();}
      const now=BigInt(Math.floor(Date.now()/1000)); const duration=BigInt(Number(listingDays)||30)*86400n;const listingHash=await writeContractAsync({chainId:8453,address:marketAddress,abi:nftMarketplaceAbi,functionName:"createListing",args:[collection,tokenId,BigInt(saleQuantity),parseEther(salePrice),now,now+duration]});setNotice("Listing submitted. Waiting for confirmation…");await publicClient?.waitForTransactionReceipt({hash:listingHash});
      setNotice("Listing is live.");setCommerceDialog(null);
    } catch(error){setNotice(shortError(error));}
  }
  async function buy() { if(!address||!selectedListing.data)return; try { const qty=safePositiveBigInt(buyQuantity); if(!qty)throw new Error("Enter a valid purchase quantity.");const hash=await writeContractAsync({chainId:8453,address:listingMarketplace,abi:nftMarketplaceAbi,functionName:"buy",value:selectedListing.data[3]*qty,args:[parsedListingId,qty,address]});setNotice("Purchase submitted. Waiting for confirmation…");await publicClient?.waitForTransactionReceipt({hash});setNotice("Purchase confirmed.");setCommerceDialog(null);void selectedListing.refetch();void balance.refetch(); } catch(error){setNotice(shortError(error));} }
  async function cancelSale() { if(!parsedListingId)return;try{const hash=await writeContractAsync({chainId:8453,address:listingMarketplace,abi:nftMarketplaceAbi,functionName:"cancelListing",args:[parsedListingId]});setNotice("Cancellation submitted. Waiting for confirmation…");await publicClient?.waitForTransactionReceipt({hash});setNotice("Listing cancelled.");void selectedListing.refetch();}catch(error){setNotice(shortError(error));} }

  const mintedCount=minted.data??0n;const maxSupply=max.data??0n;const mintAmount=safePositiveBigInt(quantity)??0n;
  const primaryMint = <section className="nft-compact-mint"><header><div><span>PRIMARY MINT</span><h2>Mint this edition</h2></div><strong>{unitPrice===0n?"FREE":`${formatEther(unitPrice)} ETH`}</strong></header>{phaseId===0n||!phaseData?<p className="nft-compact-empty">{phaseLoading?"Loading mint phase…":"No mint phase is configured."}</p>:<><MintPhaseStatus phaseType={phaseType} start={phaseData[4]} end={phaseData[5]} now={nowSeconds}/>{phaseType===1?<p className="nft-compact-note">{allowlistProof.loading?"Checking wallet eligibility…":allowlistProof.entry?`Eligible · allowance ${allowlistProof.entry.allowance}`:"This wallet is not on the active allowlist."}</p>:null}<div className="nft-compact-mint-row"><div className="field"><label>Quantity <small>Max {mintLimit > 0n ? String(mintLimit) : "—"}</small></label><input min="1" max={mintLimit > 0n ? String(mintLimit) : "1"} type="number" value={quantity} onChange={(e)=>setQuantity(e.target.value)}/></div><div className="nft-mint-total"><small>TOTAL</small><strong>{unitPrice*mintAmount===0n?"Free":`${formatEther(unitPrice*mintAmount)} ETH`}</strong></div></div><button className="button primary nft-mint-button" disabled={!canMint} onClick={()=>void mint()}>{isPending?<Loader2 className="spin"/>:<ShoppingBag/>}Mint {quantity}</button><p className="nft-compact-note">{mintAvailability}</p></>}</section>;

  if(view === "collection") return <div className={`nft-home nft-drop-home ${mintFinished ? "mint-complete" : ""}`}><NFTCollectionProfile collection={collection} name={name.data||"Edition collection"} symbol={symbol.data||"NFT"} description={collectionMetadata.description||metadata.description||(mintFinished?"Primary mint is complete. Explore and trade every edition.":"Collect an edition directly from the creator.")} image={collectionMetadata.image?ipfsGateway(collectionMetadata.image):metadata.image?ipfsGateway(metadata.image):undefined} creator={owner.data} standard="ERC-1155" supply={maxSupply} minted={mintedCount} royaltyBps={BigInt(royaltyBps.data??0)} status={mintFinished?"Mint complete":"Live mint"} socials={socialsFromMetadata(collectionMetadata)} mintPanel={mintFinished?null:primaryMint}/><NFTCollectionTabs collection={collection} offers={<NFTOffersPanel collection={collection} standard="ERC1155" mode="collection"/>}><EditionCollectionGrid collection={collection}/></NFTCollectionTabs>{notice?<p className="nft-status">{notice}</p>:null}</div>;

  return <div className="pfp-detail-page"><div className="nft-item-page">
    <section className="card nft-item-art">{metadata.image ? <img src={ipfsGateway(metadata.image)} alt={metadata.name || "NFT"}/> : <div><Sparkles/></div>}</section>
    <section className="nft-item-content"><span className="eyebrow">{name.data || "BlueFun collection"} · {symbol.data || "NFT"} · ERC-1155</span><h1>{metadata.name || `Token #${tokenId}`}</h1><p>{metadata.description || "Metadata loading…"}</p><div className="pfp-item-links"><Link href={`/nft/${collection}`}>Collection</Link><a href={`https://opensea.io/assets/base/${collection}/${tokenId}`} target="_blank" rel="noreferrer">OpenSea <ExternalLink/></a></div><div className="nft-supply"><span>Minted <b>{String(minted.data ?? 0n)}</b></span><span>Max supply <b>{String(max.data ?? 0n)}</b></span><span>Your balance <b>{String(balance.data??0n)}</b></span></div>{listingMatchesItem&&selectedListing.data?<section className="nft-quick-trade listed"><div><small>CURRENT PRICE</small><strong>{formatEther(selectedListing.data[3])} ETH</strong><span>{String(selectedListing.data[6])} available</span></div>{isListingSeller?<button className="button" disabled={isPending} onClick={()=>void cancelSale()}>Cancel listing</button>:<div className="nft-quick-buy"><input aria-label="Purchase quantity" min="1" max={String(selectedListing.data[6])} value={buyQuantity} onChange={(e)=>setBuyQuantity(e.target.value)}/><button className="button primary" disabled={!isConnected||isPending} onClick={()=>setCommerceDialog("buy")}>Buy now</button></div>}</section>:ownsEdition?<section className="nft-quick-trade"><div><small>LIST FOR SALE</small><div className="nft-edition-list-inputs"><input aria-label="Listing quantity" min="1" max={String(balance.data??1n)} value={saleQuantity} onChange={(e)=>setSaleQuantity(e.target.value)}/><div className="nft-input-suffix"><input aria-label="Sale price" min="0" type="number" value={salePrice} onChange={(e)=>setSalePrice(e.target.value)}/><span>ETH</span></div><select aria-label="Listing duration" value={listingDays} onChange={(e)=>setListingDays(e.target.value)}><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option></select></div></div><button className="button primary" disabled={isPending||!safePositiveBigInt(saleQuantity)||safeParseEther(salePrice)<=0n} onClick={()=>setCommerceDialog("list")}>Review listing</button></section>:null}{!mintFinished?<Link className="nft-inline-mint" href={`/nft/${collection}`}><Sparkles/>Primary mint is live · Open collection</Link>:null}</section>
  </div><NFTOffersPanel collection={collection} tokenId={tokenId} standard="ERC1155" ownsItem={ownsEdition}/>{isOwner ? <CreatorTools collection={collection} tokenId={tokenId} symbol={symbol.data || "NFT"} controllerAddress={controllerAddress} /> : null}{notice?<p className="nft-status">{notice}</p>:null}<code className="nft-contract">{collection} / {String(tokenId)}</code>{commerceDialog && (commerceDialog === "list" || (selectedListing.data && listingMatchesItem)) ? <NFTCommerceDialog kind={commerceDialog} title={metadata.name || `Token #${tokenId}`} collectionName={name.data || "BlueFun collection"} image={metadata.image ? ipfsGateway(metadata.image) : undefined} unitPrice={commerceDialog === "buy" && selectedListing.data ? selectedListing.data[3] : safeParseEther(salePrice)} quantity={commerceDialog === "buy" ? (safePositiveBigInt(buyQuantity) || 1n) : (safePositiveBigInt(saleQuantity) || 1n)} platformFeeBps={BigInt(marketplaceFeeBps.data ?? 80)} royaltyBps={BigInt(royaltyBps.data ?? 0)} durationDays={Number(listingDays)} needsApproval={!approved.data} pending={isPending} onClose={()=>setCommerceDialog(null)} onConfirm={()=>void (commerceDialog === "buy" ? buy() : approveOrList())}/> : null}
  </div>;
}
function shortError(error:unknown){return error instanceof Error?error.message.split("Request Arguments:")[0].slice(0,220):"Transaction failed.";}
function safeParseEther(value:string){try{return parseEther(value||"0");}catch{return 0n;}}
function safeUnsignedBigInt(value:string){return /^\d+$/.test(value)?BigInt(value):undefined;}
function safePositiveBigInt(value:string){const parsed=safeUnsignedBigInt(value);return parsed&&parsed>0n?parsed:undefined;}
function remaining(limit:bigint,used:bigint){return limit===0n?2n**256n-1n:limit>used?limit-used:0n;}
function minPositive(...values:bigint[]){return values.reduce((smallest,value)=>value<smallest?value:smallest,values[0]??0n);}
type CollectionMetadata={description?:string;image?:string;external_link?:string;external_url?:string;socials?:{website?:string;x?:string;twitter?:string;telegram?:string}};
function socialsFromMetadata(metadata:CollectionMetadata){return{...metadata.socials,website:metadata.socials?.website||metadata.external_link||metadata.external_url};}

type EditionItem = { token_id: string; max_supply: string; lifetime_minted: string; metadata_uri: string };
type EditionListing = { listingId: string; tokenId: string; unitPrice: string; priceEth: string; remaining: string; standard: string; marketplace: `0x${string}`; listedAt?: string };

function EditionCollectionGrid({collection}:{collection:`0x${string}`}){
  const [items,setItems]=useState<EditionItem[]>([]);const [listings,setListings]=useState<EditionListing[]>([]);const [selected,setSelected]=useState<NFTQuickBuyItem>();const [status,setStatus]=useState<"all"|"listed"|"unlisted">("all");const [search,setSearch]=useState("");const [sort,setSort]=useState("listed");const [page,setPage]=useState(1);const [view,setView]=useState<"grid"|"list">("grid");const pageSize=view==="grid"?24:50;
  useEffect(()=>{let active=true;const loadItems=()=>fetch(`/api/nft/items?collection=${collection}&limit=2000`).then((r)=>r.ok?r.json():{items:[]}).then((data:{items?:EditionItem[]})=>{if(active)setItems(data.items||[]);});const loadListings=()=>fetch(`/api/nft/listing?collection=${collection}&limit=2000`).then((r)=>r.ok?r.json():{listings:[]}).then((data:{listings?:EditionListing[]})=>{if(active)setListings((data.listings||[]).filter((item)=>item.standard==="ERC1155"&&item.unitPrice&&item.marketplace));});void Promise.all([loadItems(),loadListings()]);const timer=window.setInterval(loadListings,4_000);return()=>{active=false;window.clearInterval(timer);};},[collection]);
  const listingMap=useMemo(()=>new Map(listings.map((item)=>[String(item.tokenId),item])),[listings]);
  const filtered=useMemo(()=>{const exact=/^#?\d+$/.test(search.trim())?search.trim().replace("#",""):"";const rows=items.filter((item)=>{const listed=listingMap.has(String(item.token_id));return(!exact||String(item.token_id)===exact)&&(status==="all"||status==="listed"&&listed||status==="unlisted"&&!listed);});rows.sort((a,b)=>{const al=listingMap.get(String(a.token_id));const bl=listingMap.get(String(b.token_id));if(sort==="newest")return Number(b.token_id)-Number(a.token_id);if(sort==="oldest")return Number(a.token_id)-Number(b.token_id);if(sort==="listing-new")return new Date(bl?.listedAt||0).getTime()-new Date(al?.listedAt||0).getTime();if(al&&bl&&sort==="price-high")return Number(bl.priceEth)-Number(al.priceEth);if(al&&bl)return Number(al.priceEth)-Number(bl.priceEth);if(al)return -1;if(bl)return 1;return Number(a.token_id)-Number(b.token_id);});return rows;},[items,listingMap,search,sort,status]);
  useEffect(()=>setPage(1),[search,sort,status,view]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  return <section className="nft-directory-panel nft-items-panel nft-marketplace-panel" id="collection-marketplace"><header><div><span>COLLECTION MARKETPLACE</span><h2>Explore, list and trade</h2><p>Buy active listings instantly, or open an item for ownership and trait details.</p></div><div className="nft-market-stats"><strong>{items.length} ITEMS</strong><strong>{listings.length} LISTED</strong></div></header><div className="nft-market-toolbar"><label><Search/><input aria-label="Search token ID" placeholder="Search by token ID" value={search} onChange={(e)=>setSearch(e.target.value)}/></label><div className="nft-market-status"><button className={status==="all"?"active":""} onClick={()=>setStatus("all")}>All</button><button className={status==="listed"?"active":""} onClick={()=>setStatus("listed")}>Listed <b>{listings.length}</b></button><button className={status==="unlisted"?"active":""} onClick={()=>setStatus("unlisted")}>Not listed</button></div><select aria-label="Sort NFTs" value={sort} onChange={(e)=>setSort(e.target.value)}><option value="listed">Listed first</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="listing-new">Newly listed</option><option value="newest">Recently created</option><option value="oldest">Oldest</option></select><div className="nft-view-switch"><button aria-label="Grid view" className={view==="grid"?"active":""} onClick={()=>setView("grid")}><Grid2X2/></button><button aria-label="List view" className={view==="list"?"active":""} onClick={()=>setView("list")}><ListIcon/></button></div></div>{visible.length?<div className={`nft-market-items ${view}`}>{visible.map((item)=><EditionItemCard collection={collection} item={item} key={item.token_id} listing={listingMap.get(String(item.token_id))} view={view} onBuy={setSelected}/>)}</div>:<div className="nft-directory-empty"><h3>No editions match this view</h3><p>Try a different filter or token ID.</p></div>}{pages>1?<footer className="nft-market-pagination"><span>Showing {(safePage-1)*pageSize+1}–{Math.min(safePage*pageSize,filtered.length)} of {filtered.length}</span><div><button disabled={safePage===1} onClick={()=>setPage((v)=>Math.max(1,v-1))}><ChevronLeft/>Previous</button><b>Page {safePage} of {pages}</b><button disabled={safePage===pages} onClick={()=>setPage((v)=>Math.min(pages,v+1))}>Next<ChevronRight/></button></div></footer>:null}<NFTQuickBuyDialog item={selected} onClose={()=>setSelected(undefined)} onPurchased={(purchased)=>setListings((rows)=>rows.map((row)=>row.listingId===purchased.listingId&&row.marketplace.toLowerCase()===purchased.marketplace.toLowerCase()?{...row,remaining:String(Math.max(0,Number(row.remaining)-1))}:row).filter((row)=>Number(row.remaining)>0))}/></section>;
}

function EditionItemCard({collection,item,listing,view,onBuy}:{collection:`0x${string}`;item:EditionItem;listing?:EditionListing;view:"grid"|"list";onBuy:(item:NFTQuickBuyItem)=>void}){
  const [metadata,setMetadata]=useState<{name?:string;image?:string}>({});
  useEffect(()=>{if(!item.metadata_uri)return;const controller=new AbortController();fetch(ipfsGateway(item.metadata_uri),{signal:controller.signal}).then((r)=>r.ok?r.json():{}).then(setMetadata).catch(()=>undefined);return()=>controller.abort();},[item.metadata_uri]);const image=optimizedTokenImageUrl(metadata.image);
  return <article className={`nft-collection-card nft-item-card ${listing?"listed":""} ${view}`}><Link className="nft-card-link" href={`/nft/${collection}/${item.token_id}`} aria-label={`Open ${metadata.name||`Edition #${item.token_id}`}`}><div className="nft-collection-cover">{image?<img src={image} loading="lazy" decoding="async" alt={metadata.name||`Edition #${item.token_id}`}/>:<span><Sparkles/></span>}<b>#{item.token_id}</b></div><div className="nft-collection-body"><div><small>ERC-1155 · {item.lifetime_minted}/{item.max_supply} minted</small><h3>{metadata.name||`Edition #${item.token_id}`}</h3></div><footer><span>{listing?<><small>PRICE</small><strong>{listing.priceEth} ETH</strong></>:"Not listed"}</span><code>{listing?`${listing.remaining} available`:"Edition"}</code></footer></div></Link>{listing?<button className="nft-card-buy" type="button" onClick={()=>onBuy({collection,collectionName:"BlueFun collection",image,listingId:listing.listingId,marketplace:listing.marketplace,remaining:listing.remaining,standard:"ERC1155",title:metadata.name||`Edition #${item.token_id}`,tokenId:String(item.token_id),unitPrice:listing.unitPrice})}><span><b>Buy now</b><small>Instant checkout</small></span><strong>{listing.priceEth} ETH</strong></button>:null}</article>;
}

function CreatorTools({ collection, tokenId, symbol, controllerAddress }: { collection:`0x${string}`; tokenId:bigint; symbol:string; controllerAddress: `0x${string}` }) {
  const { address } = useAccount(); const { writeContractAsync, isPending } = useWriteContract();
  const nextId = useReadContract({address:collection,abi:blueEditionAbi,functionName:"nextTokenId",chainId:8453});
  const [itemName,setItemName]=useState(""); const [itemSupply,setItemSupply]=useState("100"); const [image,setImage]=useState("");
  const [itemStatus,setItemStatus]=useState(""); const [phasePrice,setPhasePrice]=useState("0"); const [phaseLimit,setPhaseLimit]=useState("2");
  async function upload(file?:File){if(!file)return;setItemStatus("Uploading artwork…");try{const form=new FormData();form.append("image",file);const response=await fetch("/api/pinata/image",{method:"POST",body:form});const data=await response.json() as {imageUri?:string;error?:string};if(!response.ok||!data.imageUri)throw new Error(data.error);setImage(data.imageUri);setItemStatus("Artwork ready.");}catch(error){setItemStatus(shortError(error));}}
  async function createItem(){if(!address||!itemName||!image)return;try{const parsedSupply=safePositiveBigInt(itemSupply);if(!parsedSupply)throw new Error("Enter a valid lifetime supply.");setItemStatus("Preparing new edition metadata…");const response=await fetch("/api/pinata/nft-metadata",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:itemName,symbol,description:"",image,supply:Number(parsedSupply),royaltyBps:0,royaltyRecipient:address})});const data=await response.json() as {itemURI?:string;error?:string};if(!response.ok||!data.itemURI)throw new Error(data.error||"Metadata could not be prepared.");await writeContractAsync({chainId:8453,address:collection,abi:blueEditionAbi,functionName:"createItem",args:[data.itemURI,parsedSupply]});setItemStatus(`New edition transaction submitted. Expected token ID: ${String(nextId.data||"")}`);}catch(error){setItemStatus(shortError(error));}}
  async function createPhase(){try{const limit=Number(phaseLimit);if(!Number.isSafeInteger(limit)||limit<1||limit>4_294_967_295)throw new Error("Enter a valid wallet limit.");const mintPrice=parseEther(phasePrice||"0");const now=BigInt(Math.floor(Date.now()/1000)+300);await writeContractAsync({chainId:8453,address:controllerAddress,abi:nftDropControllerAbi,functionName:"createPhase",args:[collection,tokenId,{phaseType:0,limitMode:0,currency:"0x0000000000000000000000000000000000000000",mintPrice,startTime:now,endTime:now+7n*86400n,phaseSupplyCap:0n,defaultWalletLimit:limit,maxPerTransaction:Math.min(50,limit),merkleRoot:`0x${"0".repeat(64)}`}]});setItemStatus("New public mint phase transaction submitted.");}catch(error){setItemStatus(shortError(error));}}
  return <section className="card nft-action nft-creator-tools"><h2><ImagePlus/>Creator tools</h2><p>Add a new token ID to this collection with its own artwork and lifetime supply.</p><div className="nft-form-grid"><div className="field"><label>Edition name</label><input value={itemName} onChange={(e)=>setItemName(e.target.value)}/></div><div className="field"><label>Lifetime supply</label><input min="1" type="number" value={itemSupply} onChange={(e)=>setItemSupply(e.target.value)}/></div></div><label className="nft-upload"><ImagePlus/><span>{image?"New artwork ready":"Choose new artwork"}</span><input hidden type="file" accept="image/*" onChange={(e)=>void upload(e.target.files?.[0])}/></label><button className="button" disabled={isPending||!itemName||!image} onClick={()=>void createItem()}>Create new edition</button><hr/><p>Queue a new seven-day public mint phase for this token ID.</p><div className="nft-form-grid"><div className="field"><label>Price (ETH)</label><input value={phasePrice} onChange={(e)=>setPhasePrice(e.target.value)}/></div><div className="field"><label>Per-wallet limit</label><input value={phaseLimit} onChange={(e)=>setPhaseLimit(e.target.value)}/></div></div><button className="button" disabled={isPending} onClick={()=>void createPhase()}>Add public mint phase</button>{itemStatus?<p className="nft-status">{itemStatus}</p>:null}</section>;
}
